### ISSUE TITLE
关于save_textures的问题

### ISSUE THREAD

**Issue by Danny-QIN** [wuhaozhe/pytorch-nicp#4]

**Comment by Danny-QIN** [comment]
你好，试了下demo可以跑起来，但是当“save_textures = True”时运行有问题，是这块还没做么？还有导出的低模没有UV信息哇

**Comment by wuhaozhe** [comment]
Hi, currently we do not support save_textures, because the uv coordinate of template model is unknown. Maybe you can assign uv coordinate of the each vertex according to its correspondence vertex in the source model

**Comment by Danny-QIN** [comment]
ok ,  I see， Looking forward to the next Version！
